#!/bin/bash
packageLogFile="/var/log/VenusOSMonarchBMS/current"

# Source SetupHelper resources
source "/data/SetupHelper/HelperResources/IncludeHelpers"

packageAction() {
    case $1 in
        install|INSTALL)
            logMessage "Installing VenusOS Monarch BMS Service..."
            installService $packageName

            logMessage "Patching QML menu UI..."
            cp "$scriptDir/qml/PageMonarchBms.qml" "$qmlDir/"

            # Remove any previous failed attempts using our unique tag
            sed -i '/VenusOSMonarchBMS/d' "$qmlDir/PageSettings.qml"

            # Inject our menu item (at the end of VisibleItemModel)
            sed -i '/model: VisibleItemModel {/a \ \ \ \ \ \ \ \ MbSubMenu { description: qsTr("Monarch BMS"); subpage: Component { PageMonarchBms {} } } \/\/VenusOSMonarchBMS' "$qmlDir/PageSettings.qml"

            restartGui=true
            ;;

        uninstall|UNINSTALL)
            logMessage "Uninstalling VenusOS Monarch BMS..."
            removeService $packageName

            sed -i '/VenusOSMonarchBMS/d' "$qmlDir/PageSettings.qml"
            rm -f "$qmlDir/PageMonarchBms.qml"

            # Remove persisted package data
            rm -rf "/data/$packageName" "/data/setupOptions/$packageName"

            # We can, however, safely delete our own custom log folder
            rm -rf "$(dirname "$packageLogFile")"

            restartGui=true
            ;;
    esac
}

if [ $scriptAction == 'NONE' ] ; then
    standardActionPrompt
else
    packageAction $scriptAction
fi

endScript
